# Generated by Django 2.2.6 on 2019-10-27 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishinput', models.CharField(max_length=200)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Fishes')),
            ],
        ),
    ]
